FROM docker.io/library/debian:stable-slim

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    curl \
    file \
    git \
    jq \
    less \
    procps \
    python3 \
    python3-pip \
    python3-venv \
    ripgrep \
    tini \
    tree \
    unzip \
    wget \
    xz-utils \
    zip \
    ghc \
    cabal-install \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
