FROM docker.io/library/debian:stable-slim

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        bc \
        build-essential \
        ca-certificates \
        cabal-install \
        cmake \
        curl \
        dnsutils \
        fd-find \
        ffmpeg \
        file \
        git \
        graphviz \
        hyperfine \
        iproute2 \
        jq \
        just \
        less \
        lsof \
        make \
        netcat-openbsd \
        ninja-build \
        openssh-client \
        parallel \
        patch \
        pkg-config \
        poppler-utils \
        procps \
        psmisc \
        python3 \
        python3-venv \
        rename \
        ripgrep \
        socat \
        sqlite3 \
        sqlite3 \
        strace \
        time \
        tini \
        tree \
        unzip \
        wget \
        xz-utils \
        zip \
        zstd \
    && rm -rf /var/lib/apt/lists/* \
    && curl -LsSf https://astral.sh/uv/install.sh | \
        XDG_BIN_HOME=/usr/bin UV_NO_MODIFY_PATH=1 sh

WORKDIR /workspace
